upd some configs; upd `bkm` (firefoxe -> chrome)

diff --git a/scripts/bkm b/scripts/bkm
--- a/scripts/bkm
+++ b/scripts/bkm
@@ -1,39 +1,29 @@
 #!/bin/bash
+
 #
-# Makes a snapshot of firefox bookmarks for further convenient use from a file
+# Convinient way of searching in Chromes' bookmarks
 #
-base=${HOME}'/.mozilla/firefox/*/bookmarks.html'
-main="$BOOKMARKS"
-old="${HOME}/.old-bookmarks"
-new="${HOME}/.new-bookmarks"
 
-begin=$(date +%s.%N)
-echo "Updating bookmarks..."
-if [ ! -f "$main" ]; then touch "$main"; fi
-sed -ne 's/.*<A HREF="\([^"]*\).*>\([^<].*\)<\/A>/\1 "\2"/p' $base > $old
-awk '!seen[$0]++' "$old" > "$new"
-DIFF=$(diff "$main" "$new")
+BOOKMARKS_PATH="$HOME/.config/chromium/Default/Bookmarks"
 
-duration=$(echo "$(date +%s.%N) - $begin" | bc)
-t=`printf "%.2f s" $duration`
+BKM=$(jq -r "
+  .roots.bookmark_bar.children[]
+  | select(.name? == \"kroll's\")
+  | .children[]
+  | select(.name? == \"Speed Dials\")
+  | .children[]
+  | \"\(.url) -- \u001b[35m\(.name)\u001b[0m\"" "$BOOKMARKS_PATH" | fzf --ansi)
 
-diff --color "$main" "$new"
-echo "Update time: $t"
+[ -z "$BKM" ] && echo "No selection made." && exit 1
 
-if [ "$DIFF" != "" ]
-then
-    while true; do
-    read -p "Patch this bookmarks? (y/n) " yn
-    case $yn in 
-        [yY]) 
-            mv "$new" "$main"
-            echo Patched👍!;
-            break;;
-        [nN]) echo exiting...;
-            exit;;
-        *) echo invalid response;;
-    esac
-    done
+URL=$(echo "$BKM" | awk -F' -- ' '{print $1}')
+NAME=$(echo "$BKM" | awk -F' -- ' '{print $2}')
+
+if command -v xclip &>/dev/null; then
+    echo -n "$URL" | xclip -selection clipboard
 else
-    echo "no updates😿"
+    echo "xclip not found"
+    exit 1
 fi
+
+echo "Copied🐧"
diff --git a/scripts/mycast b/scripts/mycast
--- a/scripts/mycast
+++ b/scripts/mycast
@@ -1,8 +1,27 @@
 #!/bin/bash
 # screen + micro capturing
 
+if ! command -v wmctrl &> /dev/null; then
+    echo "wmctrl not found!"
+    exit 1
+fi
+
 pavucontrol & \
 killall -9 pavucontrol
+
+WINDOW=$(wmctrl -l | dmenu -l 10 -p "Select a window to record:")
+if [ -z "$WINDOW" ]; then
+    echo "None of the windows were selected. Exiting..."
+    exit 1
+fi
+
+WINDOW_ID=$(echo "$WINDOW" | awk '{print $1}')
+
+GEOMETRY=$(wmctrl -lG | grep "$WINDOW_ID" | awk '{print $3,$4,$5,$6}')
+WIDTH=$(echo "$GEOMETRY" | awk '{print $3}')
+HEIGHT=$(echo "$GEOMETRY" | awk '{print $4}')
+X=$(echo "$GEOMETRY" | awk '{print $1}')
+Y=$(echo "$GEOMETRY" | awk '{print $2}')
 
 dir=$HOME/Videos
 name=$(date | awk '{print $2 "-" $3 "-" $7}')
@@ -11,8 +30,8 @@ ffmpeg -f alsa -ac 2 -i default \
 -channel_layout stereo \
 -f x11grab \
 -framerate 30 \
--s $(xrandr --current | grep -i '*' | awk '{print $1;}') \
--i :0.0+0,0 \
+-s "${WIDTH}x${HEIGHT}" \
+-i :0.0+$X,$Y \
 -c:v libx264 \
 -preset ultrafast -crf 25 \
 -c:a aac \
